" Name:         Material
" Description:  Selenized theme
" Author:       Myself <myself@somewhere.org>
" Maintainer:   Myself <myself@somewhere.org>
" Website:      https://me.org
" License:      Public domain
" Last Updated: Tue Dec  3 15:14:34 2019

" Generated by Colortemplate v2.0.0

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'material'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (((&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')) && !has('iOS'))

hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Boolean Constant
hi! link Character Constant
hi! link Conditional Statement
hi! link Define PreProc
hi! link Debug Special
hi! link Delimiter Special
hi! link Exception Statement
hi! link Float Constant
hi! link Function Identifier
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link Macro PreProc
hi! link Number Constant
hi! link Operator Statement
hi! link PreCondit PreProc
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StorageClass Type
hi! link String Constant
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  if &background ==# 'dark'
    let g:terminal_ansi_colors = ['#212121', '#b7141f', '#457b24', '#f6981e',
          \ '#134eb2', '#560088', '#0e717c', '#efefef', '#424242', '#e83b3f',
          \ '#7aba3a', '#ffea2e', '#54a4f3', '#aa4dbc', '#26bbd1', '#d9d9d9']
    if get(g:, 'materialtheme_transp_bg', 0) && !has('gui_running')
      hi Normal guifg=#efefef guibg=NONE guisp=NONE gui=NONE cterm=NONE
      hi Terminal guifg=#efefef guibg=NONE guisp=NONE gui=NONE cterm=NONE
    else
      hi Normal guifg=#efefef guibg=#212121 guisp=NONE gui=NONE cterm=NONE
      hi Terminal guifg=#efefef guibg=#212121 guisp=NONE gui=NONE cterm=NONE
    endif
    hi ColorColumn guifg=fg guibg=#212121 guisp=NONE gui=NONE cterm=NONE
    hi Conceal guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Cursor guifg=#efefef guibg=#212121 guisp=NONE gui=NONE cterm=NONE
    hi CursorColumn guifg=#efefef guibg=#212121 guisp=NONE gui=NONE cterm=NONE
    hi CursorLine guifg=#efefef guibg=#212121 guisp=NONE gui=NONE cterm=NONE
    hi CursorLineNr guifg=#efefef guibg=#212121 guisp=NONE gui=NONE cterm=NONE
    hi DiffAdd guifg=#efefef guibg=#212121 guisp=NONE gui=reverse cterm=reverse
    hi DiffChange guifg=#efefef guibg=#212121 guisp=NONE gui=reverse cterm=reverse
    hi DiffDelete guifg=#efefef guibg=#212121 guisp=NONE gui=reverse cterm=reverse
    hi DiffText guifg=#efefef guibg=#212121 guisp=NONE gui=bold,reverse cterm=bold,reverse
    hi Directory guifg=#efefef guibg=#212121 guisp=NONE gui=NONE cterm=NONE
    hi EndOfBuffer guifg=#efefef guibg=#212121 guisp=NONE gui=NONE cterm=NONE
    hi ErrorMsg guifg=#efefef guibg=#212121 guisp=NONE gui=reverse cterm=reverse
    hi FoldColumn guifg=#efefef guibg=#212121 guisp=NONE gui=NONE cterm=NONE
    hi Folded guifg=#efefef guibg=#212121 guisp=NONE gui=italic cterm=italic
    hi IncSearch guifg=#efefef guibg=#212121 guisp=NONE gui=standout cterm=standout
    hi LineNr guifg=#efefef guibg=#212121 guisp=NONE gui=NONE cterm=NONE
    hi MatchParen guifg=#efefef guibg=#212121 guisp=NONE gui=NONE cterm=NONE
    hi ModeMsg guifg=#efefef guibg=#212121 guisp=NONE gui=NONE cterm=NONE
    hi MoreMsg guifg=#efefef guibg=#212121 guisp=NONE gui=NONE cterm=NONE
    hi NonText guifg=#efefef guibg=#212121 guisp=NONE gui=NONE cterm=NONE
    hi Pmenu guifg=#efefef guibg=#212121 guisp=NONE gui=NONE cterm=NONE
    hi PmenuSbar guifg=#efefef guibg=#212121 guisp=NONE gui=NONE cterm=NONE
    hi PmenuSel guifg=#efefef guibg=#212121 guisp=NONE gui=NONE cterm=NONE
    hi PmenuThumb guifg=#efefef guibg=#212121 guisp=NONE gui=NONE cterm=NONE
    hi Question guifg=#efefef guibg=#212121 guisp=NONE gui=NONE cterm=NONE
    hi Search guifg=#efefef guibg=#212121 guisp=NONE gui=NONE cterm=NONE
    hi SignColumn guifg=#efefef guibg=#212121 guisp=NONE gui=NONE cterm=NONE
    hi SpecialKey guifg=#efefef guibg=#212121 guisp=NONE gui=NONE cterm=NONE
    hi SpellBad guifg=#efefef guibg=#212121 guisp=#b7141f gui=NONE cterm=NONE
    hi SpellCap guifg=#efefef guibg=#212121 guisp=#134eb2 gui=NONE cterm=NONE
    hi SpellLocal guifg=#efefef guibg=#212121 guisp=#560088 gui=NONE cterm=NONE
    hi SpellRare guifg=#efefef guibg=#212121 guisp=#0e717c gui=reverse cterm=reverse
    hi StatusLine guifg=#efefef guibg=#212121 guisp=NONE gui=NONE cterm=NONE
    hi StatusLineNC guifg=#efefef guibg=#212121 guisp=NONE gui=NONE cterm=NONE
    hi TabLine guifg=#efefef guibg=#212121 guisp=NONE gui=NONE cterm=NONE
    hi TabLineFill guifg=#efefef guibg=#212121 guisp=NONE gui=NONE cterm=NONE
    hi TabLineSel guifg=#efefef guibg=#212121 guisp=NONE gui=NONE cterm=NONE
    hi Title guifg=#efefef guibg=#212121 guisp=NONE gui=NONE cterm=NONE
    hi VertSplit guifg=#efefef guibg=#212121 guisp=NONE gui=NONE cterm=NONE
    hi Visual guifg=#efefef guibg=#212121 guisp=NONE gui=NONE cterm=NONE
    hi VisualNOS guifg=#efefef guibg=#212121 guisp=NONE gui=NONE cterm=NONE
    hi WarningMsg guifg=#efefef guibg=#212121 guisp=NONE gui=NONE cterm=NONE
    hi WildMenu guifg=#efefef guibg=#212121 guisp=NONE gui=NONE cterm=NONE
    hi Comment guifg=#efefef guibg=NONE guisp=NONE gui=italic cterm=italic
    hi Constant guifg=#efefef guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Error guifg=#efefef guibg=#212121 guisp=NONE gui=reverse cterm=reverse
    hi Identifier guifg=#efefef guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Ignore guifg=#efefef guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi PreProc guifg=#efefef guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Special guifg=#efefef guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Statement guifg=#efefef guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Todo guifg=#efefef guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Type guifg=#efefef guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Underlined guifg=#efefef guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi CursorIM guifg=NONE guibg=fg guisp=NONE gui=NONE cterm=NONE
    hi ToolbarLine guifg=NONE guibg=#efefef guisp=NONE gui=NONE cterm=NONE
    hi ToolbarButton guifg=#efefef guibg=#212121 guisp=NONE gui=bold cterm=bold
    if !s:italics
      hi Folded gui=NONE cterm=NONE
      hi Comment gui=NONE cterm=NONE
    endif
    unlet s:t_Co s:italics
    finish
  endif
  " Light background
  let g:terminal_ansi_colors = ['#ece3cc', '#d2212d', '#489100', '#ad8900',
        \ '#0072d4', '#ca4898', '#009c8f', '#909995', '#d5cdb6', '#cc1729',
        \ '#428b00', '#a78300', '#006dce', '#c44392', '#00978a', '#3a4d53']
  if get(g:, 'materialtheme_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#ece3cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#ece3cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#ece3cc guibg=#909995 guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#ece3cc guibg=#909995 guisp=NONE gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=fg guibg=#ece3cc guisp=NONE gui=NONE cterm=NONE
  hi Conceal guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor guifg=#ece3cc guibg=#909995 guisp=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=#ece3cc guibg=#909995 guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=#ece3cc guibg=#909995 guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#ece3cc guibg=#909995 guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=#ece3cc guibg=#909995 guisp=NONE gui=reverse cterm=reverse
  hi DiffChange guifg=#ece3cc guibg=#909995 guisp=NONE gui=reverse cterm=reverse
  hi DiffDelete guifg=#ece3cc guibg=#909995 guisp=NONE gui=reverse cterm=reverse
  hi DiffText guifg=#ece3cc guibg=#909995 guisp=NONE gui=bold,reverse cterm=bold,reverse
  hi Directory guifg=#ece3cc guibg=#909995 guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#ece3cc guibg=#909995 guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#ece3cc guibg=#909995 guisp=NONE gui=reverse cterm=reverse
  hi FoldColumn guifg=#ece3cc guibg=#909995 guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#ece3cc guibg=#909995 guisp=NONE gui=italic cterm=italic
  hi IncSearch guifg=#ece3cc guibg=#909995 guisp=NONE gui=standout cterm=standout
  hi LineNr guifg=#ece3cc guibg=#909995 guisp=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=#ece3cc guibg=#909995 guisp=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#ece3cc guibg=#909995 guisp=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#ece3cc guibg=#909995 guisp=NONE gui=NONE cterm=NONE
  hi NonText guifg=#ece3cc guibg=#909995 guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#ece3cc guibg=#909995 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=#ece3cc guibg=#909995 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#ece3cc guibg=#909995 guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=#ece3cc guibg=#909995 guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#ece3cc guibg=#909995 guisp=NONE gui=NONE cterm=NONE
  hi Search guifg=#ece3cc guibg=#909995 guisp=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=#ece3cc guibg=#909995 guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#ece3cc guibg=#909995 guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#ece3cc guibg=#909995 guisp=#d2212d gui=NONE cterm=NONE
  hi SpellCap guifg=#ece3cc guibg=#909995 guisp=#0072d4 gui=NONE cterm=NONE
  hi SpellLocal guifg=#ece3cc guibg=#909995 guisp=#ca4898 gui=NONE cterm=NONE
  hi SpellRare guifg=#ece3cc guibg=#909995 guisp=#009c8f gui=reverse cterm=reverse
  hi StatusLine guifg=#ece3cc guibg=#909995 guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#ece3cc guibg=#909995 guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#ece3cc guibg=#909995 guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#ece3cc guibg=#909995 guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#ece3cc guibg=#909995 guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#ece3cc guibg=#909995 guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#ece3cc guibg=#909995 guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=#ece3cc guibg=#909995 guisp=NONE gui=NONE cterm=NONE
  hi VisualNOS guifg=#ece3cc guibg=#909995 guisp=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#ece3cc guibg=#909995 guisp=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#ece3cc guibg=#909995 guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#ece3cc guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Constant guifg=#ece3cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#ece3cc guibg=#909995 guisp=NONE gui=reverse cterm=reverse
  hi Identifier guifg=#ece3cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#ece3cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#ece3cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#ece3cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#ece3cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#ece3cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#ece3cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#ece3cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CursorIM guifg=NONE guibg=fg guisp=NONE gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=#ece3cc guisp=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#ece3cc guibg=#909995 guisp=NONE gui=bold cterm=bold
  if !s:italics
    hi Folded gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if &background ==# 'dark'
    if get(g:, 'materialtheme_transp_bg', 0)
      hi Normal ctermfg=255 ctermbg=NONE cterm=NONE
      hi Terminal ctermfg=255 ctermbg=NONE cterm=NONE
    else
      hi Normal ctermfg=255 ctermbg=234 cterm=NONE
      if !has('patch-8.0.0616') " Fix for Vim bug
        set background=dark
      endif
      hi Terminal ctermfg=255 ctermbg=234 cterm=NONE
    endif
    hi ColorColumn ctermfg=fg ctermbg=234 cterm=NONE
    hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=255 ctermbg=234 cterm=NONE
    hi CursorColumn ctermfg=255 ctermbg=234 cterm=NONE
    hi CursorLine ctermfg=255 ctermbg=234 cterm=NONE
    hi CursorLineNr ctermfg=255 ctermbg=234 cterm=NONE
    hi DiffAdd ctermfg=255 ctermbg=234 cterm=reverse
    hi DiffChange ctermfg=255 ctermbg=234 cterm=reverse
    hi DiffDelete ctermfg=255 ctermbg=234 cterm=reverse
    hi DiffText ctermfg=255 ctermbg=234 cterm=bold,reverse
    hi Directory ctermfg=255 ctermbg=234 cterm=NONE
    hi EndOfBuffer ctermfg=255 ctermbg=234 cterm=NONE
    hi ErrorMsg ctermfg=255 ctermbg=234 cterm=reverse
    hi FoldColumn ctermfg=255 ctermbg=234 cterm=NONE
    hi Folded ctermfg=255 ctermbg=234 cterm=italic
    hi IncSearch ctermfg=255 ctermbg=234 cterm=reverse
    hi LineNr ctermfg=255 ctermbg=234 cterm=NONE
    hi MatchParen ctermfg=255 ctermbg=234 cterm=NONE
    hi ModeMsg ctermfg=255 ctermbg=234 cterm=NONE
    hi MoreMsg ctermfg=255 ctermbg=234 cterm=NONE
    hi NonText ctermfg=255 ctermbg=234 cterm=NONE
    hi Pmenu ctermfg=255 ctermbg=234 cterm=NONE
    hi PmenuSbar ctermfg=255 ctermbg=234 cterm=NONE
    hi PmenuSel ctermfg=255 ctermbg=234 cterm=NONE
    hi PmenuThumb ctermfg=255 ctermbg=234 cterm=NONE
    hi Question ctermfg=255 ctermbg=234 cterm=NONE
    hi Search ctermfg=255 ctermbg=234 cterm=NONE
    hi SignColumn ctermfg=255 ctermbg=234 cterm=NONE
    hi SpecialKey ctermfg=255 ctermbg=234 cterm=NONE
    hi SpellBad ctermfg=255 ctermbg=234 cterm=NONE
    hi SpellCap ctermfg=255 ctermbg=234 cterm=NONE
    hi SpellLocal ctermfg=255 ctermbg=234 cterm=NONE
    hi SpellRare ctermfg=255 ctermbg=234 cterm=reverse
    hi StatusLine ctermfg=255 ctermbg=234 cterm=NONE
    hi StatusLineNC ctermfg=255 ctermbg=234 cterm=NONE
    hi TabLine ctermfg=255 ctermbg=234 cterm=NONE
    hi TabLineFill ctermfg=255 ctermbg=234 cterm=NONE
    hi TabLineSel ctermfg=255 ctermbg=234 cterm=NONE
    hi Title ctermfg=255 ctermbg=234 cterm=NONE
    hi VertSplit ctermfg=255 ctermbg=234 cterm=NONE
    hi Visual ctermfg=255 ctermbg=234 cterm=NONE
    hi VisualNOS ctermfg=255 ctermbg=234 cterm=NONE
    hi WarningMsg ctermfg=255 ctermbg=234 cterm=NONE
    hi WildMenu ctermfg=255 ctermbg=234 cterm=NONE
    hi Comment ctermfg=255 ctermbg=NONE cterm=italic
    hi Constant ctermfg=255 ctermbg=NONE cterm=NONE
    hi Error ctermfg=255 ctermbg=234 cterm=reverse
    hi Identifier ctermfg=255 ctermbg=NONE cterm=NONE
    hi Ignore ctermfg=255 ctermbg=NONE cterm=NONE
    hi PreProc ctermfg=255 ctermbg=NONE cterm=NONE
    hi Special ctermfg=255 ctermbg=NONE cterm=NONE
    hi Statement ctermfg=255 ctermbg=NONE cterm=NONE
    hi Todo ctermfg=255 ctermbg=NONE cterm=NONE
    hi Type ctermfg=255 ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=255 ctermbg=NONE cterm=NONE
    hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
    hi ToolbarLine ctermfg=NONE ctermbg=255 cterm=NONE
    hi ToolbarButton ctermfg=255 ctermbg=234 cterm=bold
    if !s:italics
      hi Folded cterm=NONE
      hi Comment cterm=NONE
    endif
    unlet s:t_Co s:italics
    finish
  endif
  " Light background
  if get(g:, 'materialtheme_transp_bg', 0) && !has('gui_running')
    hi Normal ctermfg=187 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=187 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=187 ctermbg=246 cterm=NONE
    hi Terminal ctermfg=187 ctermbg=246 cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=187 cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=187 ctermbg=246 cterm=NONE
  hi CursorColumn ctermfg=187 ctermbg=246 cterm=NONE
  hi CursorLine ctermfg=187 ctermbg=246 cterm=NONE
  hi CursorLineNr ctermfg=187 ctermbg=246 cterm=NONE
  hi DiffAdd ctermfg=187 ctermbg=246 cterm=reverse
  hi DiffChange ctermfg=187 ctermbg=246 cterm=reverse
  hi DiffDelete ctermfg=187 ctermbg=246 cterm=reverse
  hi DiffText ctermfg=187 ctermbg=246 cterm=bold,reverse
  hi Directory ctermfg=187 ctermbg=246 cterm=NONE
  hi EndOfBuffer ctermfg=187 ctermbg=246 cterm=NONE
  hi ErrorMsg ctermfg=187 ctermbg=246 cterm=reverse
  hi FoldColumn ctermfg=187 ctermbg=246 cterm=NONE
  hi Folded ctermfg=187 ctermbg=246 cterm=italic
  hi IncSearch ctermfg=187 ctermbg=246 cterm=reverse
  hi LineNr ctermfg=187 ctermbg=246 cterm=NONE
  hi MatchParen ctermfg=187 ctermbg=246 cterm=NONE
  hi ModeMsg ctermfg=187 ctermbg=246 cterm=NONE
  hi MoreMsg ctermfg=187 ctermbg=246 cterm=NONE
  hi NonText ctermfg=187 ctermbg=246 cterm=NONE
  hi Pmenu ctermfg=187 ctermbg=246 cterm=NONE
  hi PmenuSbar ctermfg=187 ctermbg=246 cterm=NONE
  hi PmenuSel ctermfg=187 ctermbg=246 cterm=NONE
  hi PmenuThumb ctermfg=187 ctermbg=246 cterm=NONE
  hi Question ctermfg=187 ctermbg=246 cterm=NONE
  hi Search ctermfg=187 ctermbg=246 cterm=NONE
  hi SignColumn ctermfg=187 ctermbg=246 cterm=NONE
  hi SpecialKey ctermfg=187 ctermbg=246 cterm=NONE
  hi SpellBad ctermfg=187 ctermbg=246 cterm=NONE
  hi SpellCap ctermfg=187 ctermbg=246 cterm=NONE
  hi SpellLocal ctermfg=187 ctermbg=246 cterm=NONE
  hi SpellRare ctermfg=187 ctermbg=246 cterm=reverse
  hi StatusLine ctermfg=187 ctermbg=246 cterm=NONE
  hi StatusLineNC ctermfg=187 ctermbg=246 cterm=NONE
  hi TabLine ctermfg=187 ctermbg=246 cterm=NONE
  hi TabLineFill ctermfg=187 ctermbg=246 cterm=NONE
  hi TabLineSel ctermfg=187 ctermbg=246 cterm=NONE
  hi Title ctermfg=187 ctermbg=246 cterm=NONE
  hi VertSplit ctermfg=187 ctermbg=246 cterm=NONE
  hi Visual ctermfg=187 ctermbg=246 cterm=NONE
  hi VisualNOS ctermfg=187 ctermbg=246 cterm=NONE
  hi WarningMsg ctermfg=187 ctermbg=246 cterm=NONE
  hi WildMenu ctermfg=187 ctermbg=246 cterm=NONE
  hi Comment ctermfg=187 ctermbg=NONE cterm=italic
  hi Constant ctermfg=187 ctermbg=NONE cterm=NONE
  hi Error ctermfg=187 ctermbg=246 cterm=reverse
  hi Identifier ctermfg=187 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=187 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=187 ctermbg=NONE cterm=NONE
  hi Special ctermfg=187 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=187 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=187 ctermbg=NONE cterm=NONE
  hi Type ctermfg=187 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=187 ctermbg=NONE cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=187 cterm=NONE
  hi ToolbarButton ctermfg=187 ctermbg=246 cterm=bold
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if &background ==# 'dark'
    if get(g:, 'materialtheme_transp_bg', 0)
      hi Normal ctermfg=LightGrey ctermbg=NONE cterm=NONE
      hi Terminal ctermfg=LightGrey ctermbg=NONE cterm=NONE
    else
      hi Normal ctermfg=LightGrey ctermbg=Black cterm=NONE
      hi Terminal ctermfg=LightGrey ctermbg=Black cterm=NONE
    endif
    hi ColorColumn ctermfg=fg ctermbg=Black cterm=NONE
    hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi CursorColumn ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi CursorLine ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi CursorLineNr ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi DiffAdd ctermfg=LightGrey ctermbg=Black cterm=reverse
    hi DiffChange ctermfg=LightGrey ctermbg=Black cterm=reverse
    hi DiffDelete ctermfg=LightGrey ctermbg=Black cterm=reverse
    hi DiffText ctermfg=LightGrey ctermbg=Black cterm=bold,reverse
    hi Directory ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi EndOfBuffer ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi ErrorMsg ctermfg=LightGrey ctermbg=Black cterm=reverse
    hi FoldColumn ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi Folded ctermfg=LightGrey ctermbg=Black cterm=italic
    hi IncSearch ctermfg=LightGrey ctermbg=Black cterm=reverse
    hi LineNr ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi MatchParen ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi ModeMsg ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi MoreMsg ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi NonText ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi Pmenu ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi PmenuSbar ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi PmenuSel ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi PmenuThumb ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi Question ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi Search ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi SignColumn ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi SpecialKey ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi SpellBad ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi SpellCap ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi SpellLocal ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi SpellRare ctermfg=LightGrey ctermbg=Black cterm=reverse
    hi StatusLine ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi StatusLineNC ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi TabLine ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi TabLineFill ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi TabLineSel ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi Title ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi VertSplit ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi Visual ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi VisualNOS ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi WarningMsg ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi WildMenu ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi Comment ctermfg=LightGrey ctermbg=NONE cterm=italic
    hi Constant ctermfg=LightGrey ctermbg=NONE cterm=NONE
    hi Error ctermfg=LightGrey ctermbg=Black cterm=reverse
    hi Identifier ctermfg=LightGrey ctermbg=NONE cterm=NONE
    hi Ignore ctermfg=LightGrey ctermbg=NONE cterm=NONE
    hi PreProc ctermfg=LightGrey ctermbg=NONE cterm=NONE
    hi Special ctermfg=LightGrey ctermbg=NONE cterm=NONE
    hi Statement ctermfg=LightGrey ctermbg=NONE cterm=NONE
    hi Todo ctermfg=LightGrey ctermbg=NONE cterm=NONE
    hi Type ctermfg=LightGrey ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=LightGrey ctermbg=NONE cterm=NONE
    hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
    hi ToolbarLine ctermfg=NONE ctermbg=LightGrey cterm=NONE
    hi ToolbarButton ctermfg=LightGrey ctermbg=Black cterm=bold
    if !s:italics
      hi Folded cterm=NONE
      hi Comment cterm=NONE
    endif
    unlet s:t_Co s:italics
    finish
  endif
  " Light background
  if get(g:, 'materialtheme_transp_bg', 0) && !has('gui_running')
    hi Normal ctermfg=Black ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=Black ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi Terminal ctermfg=Black ctermbg=LightGrey cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=Black cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi CursorColumn ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi CursorLine ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi CursorLineNr ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi DiffAdd ctermfg=Black ctermbg=LightGrey cterm=reverse
  hi DiffChange ctermfg=Black ctermbg=LightGrey cterm=reverse
  hi DiffDelete ctermfg=Black ctermbg=LightGrey cterm=reverse
  hi DiffText ctermfg=Black ctermbg=LightGrey cterm=bold,reverse
  hi Directory ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi EndOfBuffer ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi ErrorMsg ctermfg=Black ctermbg=LightGrey cterm=reverse
  hi FoldColumn ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi Folded ctermfg=Black ctermbg=LightGrey cterm=italic
  hi IncSearch ctermfg=Black ctermbg=LightGrey cterm=reverse
  hi LineNr ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi MatchParen ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi ModeMsg ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi MoreMsg ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi NonText ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi Pmenu ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi PmenuSbar ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi PmenuSel ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi PmenuThumb ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi Question ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi Search ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi SignColumn ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi SpecialKey ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi SpellBad ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi SpellCap ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi SpellLocal ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi SpellRare ctermfg=Black ctermbg=LightGrey cterm=reverse
  hi StatusLine ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi StatusLineNC ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi TabLine ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi TabLineFill ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi TabLineSel ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi Title ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi VertSplit ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi Visual ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi VisualNOS ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi WarningMsg ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi WildMenu ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi Comment ctermfg=Black ctermbg=NONE cterm=italic
  hi Constant ctermfg=Black ctermbg=NONE cterm=NONE
  hi Error ctermfg=Black ctermbg=LightGrey cterm=reverse
  hi Identifier ctermfg=Black ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=Black ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=Black ctermbg=NONE cterm=NONE
  hi Special ctermfg=Black ctermbg=NONE cterm=NONE
  hi Statement ctermfg=Black ctermbg=NONE cterm=NONE
  hi Todo ctermfg=Black ctermbg=NONE cterm=NONE
  hi Type ctermfg=Black ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=Black ctermbg=NONE cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi ToolbarButton ctermfg=Black ctermbg=LightGrey cterm=bold
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: black                #212121     ~        Black
" Color: red                  #b7141f     ~        DarkRed
" Color: green                #457b24     ~        DarkGreen
" Color: yellow               #f6981e     ~        DarkYellow
" Color: blue                 #134eb2     ~        DarkBlue
" Color: magenta              #560088     ~        DarkMagenta
" Color: cyan                 #0e717c     ~        DarkCyan
" Color: white                #efefef     ~        LightGrey
" Color: brightblack          #424242     ~        DarkGrey
" Color: brightred            #e83b3f     ~        LightRed
" Color: brightgreen          #7aba3a     ~        LightGreen
" Color: brightyellow         #ffea2e     ~        LightYellow
" Color: brightblue           #54a4f3     ~        LightBlue
" Color: brightmagenta        #aa4dbc     ~        LightMagenta
" Color: brightcyan           #26bbd1     ~        LightCyan
" Color: brightwhite          #d9d9d9     ~        White
" Term colors: black red green yellow blue magenta cyan white
" Term colors: brightblack brightred brightgreen brightyellow
" Term colors: brightblue brightmagenta brightcyan brightwhite
" Background: light
" Color: black                #ece3cc     ~        Black
" Color: red                  #d2212d     ~        DarkRed
" Color: green                #489100     ~        DarkGreen
" Color: yellow               #ad8900     ~        DarkYellow
" Color: blue                 #0072d4     ~        DarkBlue
" Color: magenta              #ca4898     ~        DarkMagenta
" Color: cyan                 #009c8f     ~        DarkCyan
" Color: white                #909995     ~        LightGrey
" Color: brightblack          #d5cdb6     ~        DarkGrey
" Color: brightred            #cc1729     ~        LightRed
" Color: brightgreen          #428b00     ~        LightGreen
" Color: brightyellow         #a78300     ~        LightYellow
" Color: brightblue           #006dce     ~        LightBlue
" Color: brightmagenta        #c44392     ~        LightMagenta
" Color: brightcyan           #00978a     ~        LightCyan
" Color: brightwhite          #3a4d53     ~        White
" Term colors: black red green yellow blue magenta cyan white
" Term colors: brightblack brightred brightgreen brightyellow
" Term colors: brightblue brightmagenta brightcyan brightwhite
" Background: any
" vim: et ts=2 sw=2
